FROM pytorch/pytorch:1.9.0-cuda10.2-cudnn7-runtime

RUN python3 -m pip install --no-cache-dir \
  jupyterlab \
  h5py \
  tqdm \
  matplotlib \
  numpy \
  ipywidgets

ENV NB_PREFIX /

CMD ["sh","-c", "jupyter lab --notebook-dir=/home/jovyan --ip=0.0.0.0 --allow-root --port=8888 --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.allow_origin='*' --NotebookApp.base_url=${NB_PREFIX} --NotebookApp.iopub_data_rate_limit=1.0e10"]
